#!/usr/bin/env bash

# Create the organisation and owner
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: ROOTid' -d '{"id":"Org1","name":"Organisation 1","description":"The First Organisation","user":{"id":"Rachel","name":"Rachel Owner"}}' 'http://localhost:8080/authorization/organizations'

# Create Sam
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: Rachel'  -d '{"id":"Sam","name":"Sam Staffman"}' 'http://localhost:8080/authorization/users'

# Create staff team
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: ROOTid' --header 'org: Org1' -d '{"id":"staff","name":"Staff", "description":"Organisation 1 Staff","metadata":{}}' 'http://localhost:8080/authorization/teams'

# Assign Sam to the staff team
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: Rachel' -d '{"users":["Sam"]}' 'http://localhost:8080/authorization/teams/staff/users'

# Create Margaret
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: Rachel'  -d '{"id":"Margaret","name":"Margaret Managerson"}' 'http://localhost:8080/authorization/users'

# Create managers team
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: ROOTid' --header 'org: Org1' -d '{"id":"managers","name":"Managers", "description":"Organisation 1 Managers","metadata":{}}' 'http://localhost:8080/authorization/teams'

# Assign Margaret to the managers team
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: Rachel' -d '{"users":["Margaret"]}' 'http://localhost:8080/authorization/teams/managers/users'

# Add a policy that, when assigned, will allow creating products
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: ROOTid' --header 'org: Org1' -d '{"id":"CreateProducts","name":"create  products","version":"1","statements":{"Statement":[{"Effect":"Allow","Action":["org1:action:create"],"Resource":["/products"],"Sid":"5","Condition":{}}]}}' 'http://localhost:8080/authorization/policies?sig=123456789'

# Add a policy that, when assigned, will allow listing products
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: ROOTid' --header 'org: Org1' -d '{"id":"ListProducts","name":"list  products","version":"1","statements":{"Statement":[{"Effect":"Allow","Action":["org1:action:list"],"Resource":["/products"],"Sid":"4","Condition":{}}]}}' 'http://localhost:8080/authorization/policies?sig=123456789'

# Allow staff to list products only
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: Rachel' -d '{"policies":[{"id": "ListProducts"}]}' 'http://localhost:8080/authorization/teams/staff/policies'

# Allow managers to create and list products
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: Rachel' -d '{"policies":[{"id": "CreateProducts"}]}' 'http://localhost:8080/authorization/teams/managers/policies'

curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: Rachel' -d '{"policies":[{"id": "ListProducts"}]}' 'http://localhost:8080/authorization/teams/managers/policies'

# Allow anyone in the organisation to check access with batch endpoint
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: ROOTid' --header 'org: Org1' -d '{"id":"CheckAccess","name":"batch access check","version":"1","statements":{"Statement":[{"Effect":"Allow","Action":["authorization:authn:batch:access"],"Resource":["authorization/batchaccess"],"Sid":"2","Condition":{}}]}}' 'http://localhost:8080/authorization/policies?sig=123456789'

curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: ROOTid' -d '{"policies":[{"id": "CheckAccess"}]}' 'http://localhost:8080/authorization/organizations/Org1/policies'
